stages:
  - build
  - deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

pages:
  image: rust:latest
  environment: deploy
  script:
  - cargo doc
  - mkdir public
  - cp -r ./target/doc/* ./public/
  artifacts:
    paths:
    - public
  except:
  - master