[package]
name = "strontium"
description = "A generic low-level process virtual machine"
version = "0.5.3"
edition = "2018"
authors = ["Moritz Riede <mriede@tuta.io>"]
repository = "https://gitlab.com/strontium-environment/vm"
readme  = "README.md"
license-file = "LICENSE"
keywords = ["vm", "language", "bytecode", "p-code-machine"]

[dependencies]
bytes = "0.4.10"
hex   = "0.3.2"